###############################################################################
# THEME
###############################################################################

[theme]
base="light"
backgroundColor="#f2e3e6"
textColor="#ec297b"
font="monospace"